baseURL = 'https://apprendregofacilement.fr/'
languageCode = 'fr-fr'
title = 'ApprentiGO'
theme = 'typo'
defaultContentLanguage = "fr"

[author]
  name = "Alexandre desir"
  email = "your-email@example.com"


[taxonomies]
  category = "categories"
  tag = "tags"

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "apprendre golang de manière idiomatique en moins de 5 minutes !"

# Appearance settings
theme = 'auto'
colorPalette = 'gotheme'
hideHeader = false

# Intro on main page, content is markdown
# homeIntroTitle = 'Salut mes apprentis!'
# homeIntroContent = """
# Ici nous allons apprendre 
# """

# Collection to display on home
homeCollectionTitle = 'posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# # Social icons
# [[params.social]]
# name = "linkedin"
# url = "https://www.linkedin.com/in/user/"
#
# [[params.social]]
# name = "medium"
# url = "https://medium.com/@user"
#
# [[params.social]]
# name = "github"
# url = "https://github.com/user"

# Main menu pages
[[params.menu]]
name = "Acceuil"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

# [[params.menu]]
# name = "tutorials"
# url = "/tutorials"
#
# [[params.menu]]
# name = "Autres"
# url = "/autre"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "your/repo"
repoid = "id"
category = "category"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme" 
